---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.100.1
  share: /rpool/k8s-nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
