expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.example.com
    className: nginx-secondary
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt

externalURL: https://harbor.example.com

harborAdminPassword: "Harbor12345"

persistence:
  persistentVolumeClaim:
    registry:
      size: 5Gi
    chartmuseum:
      size: 2Gi
    jobservice:
      size: 1Gi
    database:
      size: 2Gi
    redis:
      size: 1Gi
    trivy:
      size: 1Gi
