#tls:
#  enabled: true
#  certSecret: "minio-web-tls"
#  publicCrt: tls.crt
#  privateKey: tls.key
replicas: 2
persistence:
  size: 75Gi
service:
  type: LoadBalancer
  port: "443"
consoleService:
  type: LoadBalancer
  port: "443"
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 92.254.79.38, 80.115.30.68
  path: /
  hosts:
    - minio.
  tls:
   - secretName: minio-tls
     hosts:
       - minio

consoleIngress:
  enabled: true
  ingressClassName: nginx-secondary
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx-secondary
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - minio.
  tls:
   - secretName: minio-web-tls
     hosts:
       - minio.
resources:
  requests:
    memory: 2Gi
